homeassistant:
  url: !secret homeassistant_url
  token: !secret homeassistant_token

timezone: Europe/Oslo

locale:
  default: nb
  fallback: en

container:
  show_footer: true
  style: mr-6

views:
  - name: dashboard
    components: !include dashboard.yaml

capture:
  timeout: 10000
